#
# start database and applications, without httpd
# will reply on external web server or load balancer to direct traffic
#
# docker-compose up
#

version: '2'

services:
  db:
    image: sloppycoder/atl-postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - default

  jira:
    image: sloppycoder/atl-jira
    environment:
      - BASE_URL=$BASE_URL
    depends_on:
      - db
    volumes:
      - /data/atlassian-home:/opt/atlassian-home
    networks:
      - default
    ports:
      - "8080:8080"

  stash:
    image: sloppycoder/atl-stash
    environment:
      - BASE_URL=$BASE_URL
    volumes:
      - /data/atlassian-home:/opt/atlassian-home
    depends_on:
      - db
    networks:
      - default
    ports:
      - "7990:7990"

 jenkins:
   image: jenkins:2.7.4
   volumes:
     /data/jenkins_home:/var/jenkins_home
   networks:
     - default
   ports:
     - "18085:8080"
     - "50000:50000"
