#!/bin/bash

echo "******CREATING APPLICATIONS DATABASES ******"

export PGUSER=postgres
psql <<- EOSQL
	CREATE DATABASE jira WITH ENCODING='UTF8' TEMPLATE=template0;
	CREATE DATABASE stash WITH ENCODING='UTF8' TEMPLATE=template0;
	CREATE DATABASE bamboo WITH ENCODING='UTF8' TEMPLATE=template0;
EOSQL

echo "******APPLICATION DATABASES CREATED******"

