## TODO:
#   read AWS credential from .aws/config, then fallback to ENV variable
#

ENV["VAGRANT_DEFAULT_PROVIDER"] = "google"

$script = <<SCRIPT
  yum update -y
  yum install -y docker git dos2unix
  sudo service docker start
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "gce"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-google/raw/master/google.box"
  config.vm.provision "shell", inline: $script

  config.vm.provider :google do |google, override|
    
    #google.google_project_id = "YOUR_GOOGLE_CLOUD_PROJECT_ID"
    #google.google_client_email = "YOUR_SERVICE_ACCOUNT_EMAIL_ADDRESS"
    #google.google_key_location = "/PATH/TO/YOUR/PRIVATE_KEY.p12"
    #override.ssh.username = "USERNAME"
    #override.ssh.private_key_path = "~/.ssh/id_rsa"


    #override.ssh.username = "USERNAME"
    #override.ssh.private_key_path = "~/.ssh/id_rsa"

    google.zone = "us-central1-a"

    google.zone_config "us-central1-a" do |zone|
      zone.name = "testing-docker"
      zone.image = "centos-7-v20150127"
      zone.machine_type = "n1-standard-1"
      zone.disk_size = 10
      zone.zone = "us-central1-a"
      zone.metadata = {"name" => "docker-test"}
      zone.tags = ["docker"]
      zone.instance_ready_timeout = 30
    end

    # to avoid error like "No host IP was given to the Vagrant core NFS helper."
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Redhat Linux sudo requires tty
    config.ssh.pty = true

  end 

end
