ENV['VAGRANT_DEFAULT_PROVIDER'] = 'parallels'

$script = <<SCRIPT
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "parallels/boot2docker"
  config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.synced_folder "../data", "/vagrant_data", disabled: true

  config.vm.provider "parallels" do |v|
    v.memory = 3072
    v.cpus = 2
  end

  #config.vm.provision "shell", inline: $script
end
